name: Create and run python wheel 

on: 
  push: 
    branches: main 

  workflow_dispatch:

jobs: 
  create-and-run-wheel: 
    uses: juanzq10dev/workflows/.github/workflows/main.yml@main
    with: 
        wheel-name: Hi
        
